### PR TITLE
new codesign strategy

### PR DESCRIPTION
**Pull request by kerner1000**

### CODE REVIEW

**Comment by kerner1000** [comment]
Fixes #245

**Comment by fvarrui** [comment]
Hi @kerner1000!
Thanks so much for your contribution.
I'm not able to try on Mac OS right now ... please, can you confirm that the version of the plugin in pr-252 branch is working as expected?

**Comment by kerner1000** [comment]
Ok, I will test it!

**Comment by kerner1000** [comment]
New code signing in p-252 looks good!

**Comment by fvarrui** [comment]
PR-252 merged into `devel` branch, ready to be released!

**Pull request merged**
