### PR TITLE
Update why

### PR DESCRIPTION
**Pull request by keastrid**
Fix forwarding of launcher args (and use of the exe with file associations)

### CODE REVIEW

**Comment by fvarrui** [comment]
Thanks! I'm going to release JavaPackager 1.6.6 ... do you plan to make more updates to JavaLauncher in the short term?

**Comment by keastrid** [comment]
Thanks!
The next thing I'm working on is also for file associations - an option to instead of opening files in a new instance, open them in the current one. Though this might be a bug on the Java side of things...

There's no need to wait for me on this, I don't think most applications are making use of this with launch4j (winrun wasn't tested to my knowledge), and we can just use a local javapackager in the mean time.

**Comment by fvarrui** [comment]
Ok, perfect! Thanks

**Comment by fvarrui** [comment]
I'll release your changes, but I'm not going to document the new `why` launcher at the moment, till I can test well all different options/configurations.

**Comment by keastrid** [comment]
That's fine! If you find any issues, feel free to le me know!

**Pull request merged**
