### PR TITLE
Search PATH for JRE in Windows

### PR DESCRIPTION
**Pull request by farzadpanahi**
Most of the JRE installations in Windows (including Oracle JRE) do not add `JAVA_HOME` environment variable after installation. In this case the generated `exe` file will fail to run because it cannot find the JRE. 

This PR will include `%PATH%` along side `%JAVA_HOME%` to search for JRE. This feature is implemented in Launch4j 3.13 based on [FR 127](https://sourceforge.net/p/launch4j/feature-requests/127/). 

For this reason both maven and gradle plugins for Launch4j need to be upgraded. Maven plugin is already upgraded to 2.1.1. This PR also upgrades gradle plugin to `edu.sc.seis.launch4j:launch4j:2.5.0`

### CODE REVIEW

**Comment by fvarrui** [comment]
Hi @farzadpanahi!
Thanks so much for your contribution. There's an [issue with gradle-launch4j 2.5.0](https://github.com/fvarrui/JavaPackager/issues/119). Does your changes work with 2.4.7?

**Comment by farzadpanahi** [comment]
@fvarrui I will try to test it this week and update you.

**Comment by Hungryee** [comment]
Hello, @fvarrui 
Thank you for your amazing plugin, does to the work for me and others. The only issue is the above-mentioned problem: bundled jre in Windows EXE is not found on launch: the message says the bundled jre is missinng or corrupted. 
Could you please have a look again?

**Comment by fvarrui** [comment]
Changes have been merged into master leaving gradle-plugin v2.4.7. Now you can try to install JavaPackager v1.6.0-SNAPSHOT manually to your local repo as it's explained [here](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin).

**Pull request merged**
