### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by EasyG0ing1**
I just added GistFX to the list of applications that are packaged with JavaPackager

☺

### CODE REVIEW

**Comment by fvarrui** [comment]
Great!!! Thanks
Did you manage to build your app installer for Linux?

**Comment by EasyG0ing1** [comment]
@fvarrui - I havent tackled Linux yet ... I was still working on the program itself and have recently developed a lot of the help content for it ... getting close to a point where I can spend some time on other things... hopefully soon ... while I was working on help content I was going through all of the features of the program and discovered a lot of bugs that had to be worked out.

**Comment by fvarrui** [comment]
Ok! 💪 Let me know if I can help you

**Comment by EasyG0ing1** [comment]
@fvarrui - Well ... I think of the big three, Linux is perhaps the least documented in this project. I added a Linux config to my POM file, but when I do a mvn package on the mac, it completely ignores the Linux stuff ... Not sure if my mac is just stuck up and won't talk to lower life forms or if it's being stupid ... either way, I need to know what to do next.

☺

Here's my setup

```XML
<plugin>
<groupId>io.github.fvarrui</groupId>
<artifactId>javapackager</artifactId>
<version>1.6.5</version>
<configuration>
    <mainClass>${exec.mainClass}</mainClass>
    <bundleJre>true</bundleJre>
    <customizedJre>false</customizedJre>
    <generateInstaller>true</generateInstaller>
    <administratorRequired>false</administratorRequired>
    <copyDependencies>true</copyDependencies>
</configuration>
<executions>
    <execution>
        <id>windows</id>
        <phase>package</phase>
        <goals>
            <goal>package</goal>
        </goals>
        <configuration>
            <assetsDir>/Users/michael/IdeaProjects/GistFX/assets</assetsDir>
            <platform>auto</platform>
            <createZipball>false</createZipball>
            <createTarball>true</createTarball>
            <vmArgs>
                <vmArg>--enable-preview</vmArg>
            </vmArgs>
            <macConfig>
                <generateDmg>true</generateDmg>
                <generatePkg>true</generatePkg>
                <volumeName>GistFX</volumeName>
                <entitlements>entitlements.plist</entitlements>
                <backgroundImage>/Users/michael/IdeaProjects/GistFX/assets/mac/background.png</backgroundImage>
                <windowWidth>620</windowWidth>
                <windowHeight>480</windowHeight>
            </macConfig>
            <linuxConfig>
                <pngFile>/Users/michael/IdeaProjects/GistFX/assets/linux/GistFX.png</pngFile>
                <generateRpm>true</generateRpm>
                <generateDeb>true</generateDeb>
                <wrapJar>true</wrapJar>
            </linuxConfig>
        </configuration>
    </execution>
</executions>
</plugin>
```

**Comment by EasyG0ing1** [comment]
@fvarrui - Any particular flavor of Linux that you prefer to build in?

**Pull request merged**
