### PR TITLE
Deploy to GitHub Packages

### PR DESCRIPTION
**Pull request by kerner1000**
Make it possible to deploy (SNAPSHOT versions) to GitHub Packages.

This can be used as a SNAPSHOT repository if publishing to Maven Central is not possible or not desired yet.

### CODE REVIEW

**Comment by fvarrui** [comment]
Do you know how one can use theses packages released in GitHub Packages? I mean .. what does I have to setup in `pom.xml` or `build.gradle`?

Thanks for this interesting suggestion!!

**Comment by kerner1000** [comment]
Oh cow, something is messed up here.. 108 files changed??

**Comment by kerner1000** [comment]
... I will try to recreate this PR..

**Comment by fvarrui** [comment]
Maybe your branch was outdated?

**Comment by fvarrui** [comment]
Thanks!

**Pull request closed without merging**
