### PR TITLE
Support custom tarball name

### PR DESCRIPTION
**Pull request by kerner1000**

### CODE REVIEW

**Comment by fvarrui** [comment]
Why don't you use a plugin like [`copy-rename-maven-plugin`](https://coderplus.github.io/copy-rename-maven-plugin/rename-mojo.html) after packaging for this?

Anyway, if we finally include this new feature, it has to be extended for Gradle and offer the same for zipballs, giving coherence to the plugin. What do you think? Would you like to implement it? 😅

**Comment by kerner1000** [comment]
Oh, I did not know about copy-rename-maven-plugin :)

I will update the PR to include according changes for the grade packager and the zipball.

**Comment by kerner1000** [comment]
Updated.

**Comment by fvarrui** [comment]
Thanks so much!

**Comment by fvarrui** [comment]
Ohh ... docs should also be updated with the new plugin properties 😅

**Pull request merged**
